export const translations = {
  sv: {
    heroTitle: "Mangiare",
    heroSubtitle: "Kök & Bar",
    navMenu: "MENY",
    navCatering: "CATERING",
    navBoka: "BOKA",
    aboutText1: "Mangiare är italienska för “att äta”. För oss handlar mat om mer än bara hunger; det handlar om människor, möten och stunder att minnas.",
    aboutText2: "Här finns plats för familjemiddagar, ett glas vin med vänner, en spontan kväll ute eller en lugn middag på egen hand. På Mangiare Kök & Bar vill vi vara en varm och avslappnad kvarterskrog där alla känner sig välkomna.",
    aboutText3: "Kom som du är, stanna så länge du vill och bli en del av vår restaurang!",
    cateringText: "Vi erbjuder fullservicecatering där upplägget och priset skräddarsys helt efter era önskemål och sällskapets storlek.",
    cateringText2: "Välj bland våra färdiga koncept som sträcker sig från generösa bufféförslag till eleganta trerättersmenyer eller låt oss komponera en helt unik meny utifrån dina egna idéer.",
    cateringText3: "Oavsett om ni planerar en privat fest, en AW med kollegorna, studentmottagning eller ett större företagsevent, ser vi till att maten blir en succé.",
    cateringText4: "I vår fullservicecatering kan följande ingå:" , 
    cateringText5: "Porslin, glas och bestick.", 
    cateringText6:"Professionell serveringspersonal.",
    cateringText7: "Alkoholservering (med tillhörande barpersonal och tillstånd)",
    contactTitle: "Boka bord hos oss",
    contactSubtitle: "Vill du boka bord, eller har andra funderingar så mejla eller ring oss så hjälper vi er",
    emailUs: "Mejla oss!",
    offert: "Kontakta oss för offert!",
    phone: "Telefonnummer",
    findUs: "Hitta till oss!",
    findUsText: "Sväng förbi oss på Solviksvägen 2C, Gävle",
    address: "Adress",
    hours: "Öppettider",
    hoursText: "Alla dagar 11:00-23:00",
    partners: "Samarbetspartners",
    menu: "Meny",
    menupage: '/meny.pdf#page=1'
  },
  en: {
    heroTitle: "Mangiare",
    heroSubtitle: "Kitchen & Bar",
    navMenu: "MENU",
    navCatering: "CATERING",
    navBoka: "BOOK",
    aboutText1: "Mangiare is Italian for “to eat”. For us, food is about more than just hunger; it's about people, gatherings, and moments to remember.",
    aboutText2: "Here, there's room for family dinners, a glass of wine with friends, a spontaneous night out, or a quiet dinner on your own. At Mangiare Kitchen & Bar, we want to be a warm and relaxed neighborhood restaurant where everyone feels welcome.",
    aboutText3: "Come as you are, stay as long as you like, and become a part of our restaurant.",
    cateringText: "We offer full-service catering where the setup and price are tailored entirely to your wishes and the size of your group.",
    cateringText2: "Choose from our ready-made concepts, ranging from generous buffet options to elegant three-course menus, or let us compose a completely unique menu based on your own ideas.",
    cateringText3: "Whether you are planning a private party, an after-work event with colleagues, a graduation, or a larger corporate function, we ensure the food is a success.",
    cateringText4: "Our full-service catering can include:",
    cateringText5: "Tableware, glasses, and cutlery.",
    cateringText6: "Professional waitstaff.",
    cateringText7: "Alcohol service (including bar staff and licensing).",
    contactTitle: "Book a table",
    contactSubtitle: "Contact us if you want to make a reservation, or if you have any questions",
    emailUs: "Email us!",
    offert: "Contact us with your request!",
    phone: "Phone Number",
    findUs: "Find Us!",
    findUsText: "Drop by and see us at Solviksvägen 2C, Gävle",
    address: "Address",
    hours: "Opening Hours",
    hoursText: "All days 11:00-23:00",
    partners: "Partners",
    menu: "Menu",
    menupage: '/meny.pdf#page=8'
  }
};